/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthAvatarButton: typeof import('./../../components/auth/AuthAvatarButton.vue')['default']
    AuthAvatarNicknameDialog: typeof import('./../../components/auth/AuthAvatarNicknameDialog.vue')['default']
    AuthPhoneNumberButton: typeof import('./../../components/auth/AuthPhoneNumberButton.vue')['default']
    AvatarNickname: typeof import('./../../components/AvatarNickname.vue')['default']
    Cell: typeof import('./../../components/Cell.vue')['default']
    DateTimePicker: typeof import('./../../components/picker/DateTimePicker.vue')['default']
    Dialog: typeof import('./../../components/dialog/Dialog.vue')['default']
    FooterActionsBar: typeof import('./../../components/FooterActionsBar.vue')['default']
    FormControl: typeof import('./../../components/FormControl.vue')['default']
    FormDialog: typeof import('./../../components/dialog/FormDialog.vue')['default']
    LabelValueBar: typeof import('./../../components/LabelValueBar.vue')['default']
    Layout: typeof import('./../../components/layout/Layout.vue')['default']
    List: typeof import('./../../components/List.vue')['default']
    NavBar: typeof import('./../../components/layout/NavBar.vue')['default']
    NickNameInput: typeof import('./../../components/auth/NickNameInput.vue')['default']
    NutAnimate: typeof import('nutui-uniapp/components/animate/animate.vue')['default']
    NutAvatar: typeof import('nutui-uniapp/components/avatar/avatar.vue')['default']
    NutBadge: typeof import('nutui-uniapp/components/badge/badge.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutComment: typeof import('nutui-uniapp/components/comment/comment.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutImagePreview: typeof import('nutui-uniapp/components/imagepreview/imagepreview.vue')['default']
    NutNoticebar: typeof import('nutui-uniapp/components/noticebar/noticebar.vue')['default']
    NutSwiper: typeof import('nutui-uniapp/components/swiper/swiper.vue')['default']
    NutSwiperItem: typeof import('nutui-uniapp/components/swiperitem/swiperitem.vue')['default']
    NutTag: typeof import('nutui-uniapp/components/tag/tag.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    Picker: typeof import('./../../components/picker/Picker.vue')['default']
    Popup: typeof import('./../../components/popup/Popup.vue')['default']
    SwiperPro: typeof import('./../../components/SwiperPro.vue')['default']
    TabBar: typeof import('./../../components/layout/TabBar.vue')['default']
    TabsPaneList: typeof import('./../../components/TabsPaneList.vue')['default']
    TitleBar: typeof import('./../../components/TitleBar.vue')['default']
    UCharts: typeof import('./../../components/u-charts/u-charts.vue')['default']
    Uploader: typeof import('./../../components/Uploader.vue')['default']
  }
}
